# pre-commit 1.1.0 is required for `exclude`
# however `minimum_pre_commit_version` itself requires 1.15.0
minimum_pre_commit_version: "1.15.0"

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: [--branch, main]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
    - id: pyupgrade
      args: [--py37-plus]
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
    - id: isort
      name: isort (python)
    - id: isort
      name: isort (cython)
      types: [cython]
-   repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
    - id: flake8
      additional_dependencies: [
        flake8-bugbear==21.9.1,
        flake8-logging-format==0.6.0,
        flake8-2020==1.6.0,
      ]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
    -   id: setup-cfg-fmt
        args: [--max-py-version, '3.9']
