name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - Readme.md
      - LICENSE

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [
          macos-latest,
          # windows-latest,  # fails with error 127, skipping for the moment
          ubuntu-latest,
        ]
        python-version: ["3.10", "3.11", "3.12", "3.13-dev"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install package
      shell: bash
      run: |
        python -m pip install pytest
        python -m pip install -e .
    - name: pytest
      shell: bash
      run: pytest -v
