name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - Readme.md
      - LICENSE

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [
          macos-latest,
          # windows-latest,  # fails with error 127, skipping for the moment
          ubuntu-latest,
        ]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: s-weigand/setup-conda@v1
      if: matrix.os == 'windows-latest'
      with:
        update-conda: true
        conda-channels: conda-forge
        activate-conda: true
        python-version: ${{matrix.python-version}}
    - name: Install package
      shell: bash
      run: |
        python -m pip install pytest
        python -m pip install -e .
    - name: pytest
      shell: bash
      run: pytest -v
