name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - Readme.md
      - LICENSE

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4

      - uses: pypa/cibuildwheel@v2.11.2

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
