name: Build

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - Readme.md
      - LICENSE

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - uses: pypa/cibuildwheel@v2.2.2
        with:
          output-dir: wheelhouse
          config-file: pyproject.toml

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
